### PR TITLE
Fix endians

### PR DESCRIPTION
**Pull request by mortenvp**

### CODE REVIEW

**Comment by mortenvp** [comment]
@looopTools a few comments:

* There seems to be quite a bit of redundancy between the reader and writer in calculating the the sizes and offsets I think we can split that into a helper file which can contain this functionality and be tested independently.

* I think we should remove all the `uint8_t` pointers from the API and only work on the values. That way we can also avoid having to read a single bit at a time.

* Also remove the `convert_endian` function, no need for that dependency here. The user can do that himself if he wants that functionality. We can have it as an internal dependency to the project so that we can use it in the examples and unit tests.

**Comment by looopTools** [comment]
@mortenvp 
1. We can do that, but would you prefer a helper file or inheritance
2. How would you read a 1 bit flag with out reading a single bit? 
3. I cannot get the test to work without `convert_endian`, because it is ruined by endianness on the mips, as the read function does not work. How should this be fixed?

**Comment by mortenvp** [comment]
1. I would prefer a help file.

2. From the size of the flag you can derive a mask that can be used to get the bits you want. Summing sizes up to the desired flag will give you the bit offset into the value i.e.  the amount of shifts. 

3. It should be possible to test the reader and writer without any endianess. However it would be great also to have a unit test that tests converting endianess of the written or read value.

I can take a stab at creating some of the help of functionality that I think we would need for creating the mask etc. unless you want to give it a shot yourself first.

**Comment by looopTools** [comment]
@mortenvp how would you avoid endianness when you are shifting on value? 
If we have the value `n = 128` and `n` is 16 bit. Then on Little Endian it will be written `00000000 10000000` whilst on Big Endian it will be `10000000 00000000` and therefore if we shift, we end up with problems again. anyways I will try, maybe I did something wrong

**Comment by mortenvp** [comment]
The endianess problem only exists when you write the value. If you work on the value the bits are always located the same place. Bitter will not write the value endian will so it does not have to worry about it.

Makes sense?

**Comment by looopTools** [comment]
@mortenvp Yes make sense, I will implemented ASAP. 

And thanks :)

**Comment by mortenvp** [comment]
Write when you want some feedback.

**Pull request merged**
